name: TelegramChat
main: de.Linus122.TelegramChat.TelegramChat
version: ${project.version}
api-version: 1.17
authors: [Linus122]
softdepend: [Vault]
description: Brings minecraft chat to Telegram!
commands:
   telegram:
      description: Main command
      usage: /<command> [token]
      permission: telegram.settoken
   linktelegram:
      description: Main command
      usage: /<command>
      permission: telegram.linktelegram
